# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherHub

    pod 'Charts'
    pod 'Alamofire'
    pod 'SwiftRecord'
    pod 'ReachabilitySwift'

  target 'WeatherHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
